// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBun1Z1BKjD2kmAEryrxFCHaKes38RShcM',
    appId: '1:528339674320:web:86006242bb31455f5d6ad5',
    messagingSenderId: '528339674320',
    projectId: 'raffl-2ec83',
    authDomain: 'raffl-2ec83.firebaseapp.com',
    storageBucket: 'raffl-2ec83.appspot.com',
    measurementId: 'G-DD215G52ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDylneigkjtChp8aeHIBjRk1IN0fVrR8rI',
    appId: '1:528339674320:android:0a9604af4c5d13965d6ad5',
    messagingSenderId: '528339674320',
    projectId: 'raffl-2ec83',
    storageBucket: 'raffl-2ec83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtTPVyAGOH5gbMZjTKKy_qQy-OH_k8i8w',
    appId: '1:528339674320:ios:42f94a50f7aa5dac5d6ad5',
    messagingSenderId: '528339674320',
    projectId: 'raffl-2ec83',
    storageBucket: 'raffl-2ec83.appspot.com',
    iosBundleId: 'com.example.raffl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtTPVyAGOH5gbMZjTKKy_qQy-OH_k8i8w',
    appId: '1:528339674320:ios:be20dc7a4f5d2ed75d6ad5',
    messagingSenderId: '528339674320',
    projectId: 'raffl-2ec83',
    storageBucket: 'raffl-2ec83.appspot.com',
    iosBundleId: 'com.example.raffl.RunnerTests',
  );
}
